//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deputaty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deputaty()
        {
            this.Zakonoproekts = new HashSet<Zakonoproekt>();
            this.Golosovanie_za_kriteriy = new HashSet<Golosovanie_za_kriteriy>();
            this.Komitets = new HashSet<Komitet>();
            this.Frakciyas = new HashSet<Frakciya>();
            this.Pomoshnik_deputata_ = new HashSet<Pomoshnik_deputata_>();
            this.Otvetstvennie_za_versiyu = new HashSet<Otvetstvennie_za_versiyu>();
            this.Versiya_feature = new HashSet<Versiya_feature>();
            this.Sozyvies = new HashSet<Sozyvy>();
        }

        public override string ToString()
        {
            return "["+ Partiyniy_bilet+"]" +" "+Familiya + " " + Imya;
        }

        public int Partiyniy_bilet { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestovo { get; set; }
        public string Region_vyborov { get; set; }
        public int ID_frakcii { get; set; }
        public int ID_komiteta { get; set; }
        public Nullable<System.DateTime> Data_rozhdeniya { get; set; }
    
        public virtual Frakciya Frakciya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakonoproekt> Zakonoproekts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Golosovanie_za_kriteriy> Golosovanie_za_kriteriy { get; set; }
        public virtual Komitet Komitet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komitet> Komitets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Frakciya> Frakciyas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pomoshnik_deputata_> Pomoshnik_deputata_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otvetstvennie_za_versiyu> Otvetstvennie_za_versiyu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Versiya_feature> Versiya_feature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sozyvy> Sozyvies { get; set; }
    }
}
