//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Golosovanie_za_kriteriy
    {
        public int ID_statusa_kriteriya { get; set; }
        public int Deputat { get; set; }
        public bool Za_Protiv { get; set; }
    
        public virtual Deputaty Deputaty { get; set; }
        public virtual Status_kriteriya Status_kriteriya { get; set; }
    }
}
