//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komitet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Komitet()
        {
            this.Deputaties = new HashSet<Deputaty>();
        }

        public override string ToString()
        {
            return Naimenovanie;
        }

        public int ID { get; set; }
        public string Naimenovanie { get; set; }
        public string Website { get; set; }
        public int God_osnovaniya { get; set; }
        public int Kolichestvo_chlenov { get; set; }
        public int Kolichestvo_chlenov_posledniy_sozyv { get; set; }
        public Nullable<int> Glava_komiteta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deputaty> Deputaties { get; set; }
        public virtual Deputaty Deputaty { get; set; }
    }
}
