//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesto_provedeniya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mesto_provedeniya()
        {
            this.Zasedanies = new HashSet<Zasedanie>();
        }

        public override string ToString()
        {
            return Ulica + " " + Dom;
        }

        public int ID { get; set; }
        public string Gorod { get; set; }
        public string Ulica { get; set; }
        public int Dom { get; set; }
        public Nullable<int> Korpus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zasedanie> Zasedanies { get; set; }
    }
}
