//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otvetstvennie_za_versiyu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Otvetstvennie_za_versiyu()
        {
            this.Versiya_feature = new HashSet<Versiya_feature>();
        }
    
        public int ID { get; set; }
        public int Versiya { get; set; }
        public int Deputat { get; set; }
    
        public virtual Deputaty Deputaty { get; set; }
        public virtual Versiya_ZP Versiya_ZP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Versiya_feature> Versiya_feature { get; set; }
    }
}
