//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pomoshnik_deputata_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pomoshnik_deputata_()
        {
            this.Sphera_deyatelnosti = new HashSet<Sphera_deyatelnosti>();
        }
    
        public int Udostoverenie { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestovo { get; set; }
        public string Grajdanstvo { get; set; }
        public System.DateTime Data_rozhdeniya { get; set; }
        public Nullable<int> Frakciya { get; set; }
        public int Patron { get; set; }
    
        public virtual Deputaty Deputaty { get; set; }
        public virtual Frakciya Frakciya1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sphera_deyatelnosti> Sphera_deyatelnosti { get; set; }
    }
}
