//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rassmotrenie_ZP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rassmotrenie_ZP()
        {
            this.Status_kriteriya = new HashSet<Status_kriteriya>();
        }
    
        public int Nomer_rassmotreniya { get; set; }
        public int Nomer_zasedaniya { get; set; }
        public int ID_zakonoproekta { get; set; }
    
        public virtual Zasedanie Zasedanie { get; set; }
        public virtual Zakonoproekt Zakonoproekt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status_kriteriya> Status_kriteriya { get; set; }
    }
}
