//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sozyvy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sozyvy()
        {
            this.Predsedatels = new HashSet<Predsedatel>();
            this.Zasedanies = new HashSet<Zasedanie>();
            this.Deputaties = new HashSet<Deputaty>();
        }
    
        public int Nomer { get; set; }
        public Nullable<int> Konstitucionnoe_bolshinstvo { get; set; }
        public Nullable<System.DateTime> Data_nachala { get; set; }
        public Nullable<System.DateTime> Data_konca { get; set; }
    
        public virtual Frakciya Frakciya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predsedatel> Predsedatels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zasedanie> Zasedanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deputaty> Deputaties { get; set; }
    }
}
