//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_kriteriya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Status_kriteriya()
        {
            this.Golosovanie_za_kriteriy = new HashSet<Golosovanie_za_kriteriy>();
        }
    
        public int ID { get; set; }
        public int Nomer_rassmotreniya { get; set; }
        public int ID_kriteriya { get; set; }
        public Nullable<bool> Odobren { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Golosovanie_za_kriteriy> Golosovanie_za_kriteriy { get; set; }
        public virtual Kriteriy Kriteriy { get; set; }
        public virtual Rassmotrenie_ZP Rassmotrenie_ZP { get; set; }
    }
}
