//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class The_State_Duma_Entities : DbContext
    {
        public The_State_Duma_Entities(string conn_str)
            : base(conn_str)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deputaty> Deputaties { get; set; }
        public virtual DbSet<Frakciya> Frakciyas { get; set; }
        public virtual DbSet<Golosovanie_za_kriteriy> Golosovanie_za_kriteriy { get; set; }
        public virtual DbSet<Gruppovaya_rabota> Gruppovaya_rabota { get; set; }
        public virtual DbSet<Komitet> Komitets { get; set; }
        public virtual DbSet<Kriteriy> Kriteriys { get; set; }
        public virtual DbSet<Mesto_provedeniya> Mesto_provedeniya { get; set; }
        public virtual DbSet<Otvetstvennie_za_versiyu> Otvetstvennie_za_versiyu { get; set; }
        public virtual DbSet<Pomoshnik_deputata_> Pomoshnik_deputata_ { get; set; }
        public virtual DbSet<Predsedatel> Predsedatels { get; set; }
        public virtual DbSet<Rassmotrenie_ZP> Rassmotrenie_ZP { get; set; }
        public virtual DbSet<Sozyvy> Sozyvies { get; set; }
        public virtual DbSet<Sphera_deyatelnosti> Sphera_deyatelnosti { get; set; }
        public virtual DbSet<Status_kriteriya> Status_kriteriya { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Versiya_feature> Versiya_feature { get; set; }
        public virtual DbSet<Versiya_ZP> Versiya_ZP { get; set; }
        public virtual DbSet<Zakonoproekt> Zakonoproekts { get; set; }
        public virtual DbSet<Zasedanie> Zasedanies { get; set; }
    
        [DbFunction("The_State_Duma_Entities", "DistributionOfDeputies")]
        public virtual IQueryable<DistributionOfDeputies_Result> DistributionOfDeputies(Nullable<int> sozyv)
        {
            var sozyvParameter = sozyv.HasValue ?
                new ObjectParameter("Sozyv", sozyv) :
                new ObjectParameter("Sozyv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DistributionOfDeputies_Result>("[The_State_Duma_Entities].[DistributionOfDeputies](@Sozyv)", sozyvParameter);
        }
    
        [DbFunction("The_State_Duma_Entities", "DistributionOfDeputiesIncludeAges")]
        public virtual IQueryable<DistributionOfDeputiesIncludeAges_Result> DistributionOfDeputiesIncludeAges(Nullable<int> sozyv, Nullable<int> age_start, Nullable<int> age_end)
        {
            var sozyvParameter = sozyv.HasValue ?
                new ObjectParameter("Sozyv", sozyv) :
                new ObjectParameter("Sozyv", typeof(int));
    
            var age_startParameter = age_start.HasValue ?
                new ObjectParameter("Age_start", age_start) :
                new ObjectParameter("Age_start", typeof(int));
    
            var age_endParameter = age_end.HasValue ?
                new ObjectParameter("Age_end", age_end) :
                new ObjectParameter("Age_end", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DistributionOfDeputiesIncludeAges_Result>("[The_State_Duma_Entities].[DistributionOfDeputiesIncludeAges](@Sozyv, @Age_start, @Age_end)", sozyvParameter, age_startParameter, age_endParameter);
        }
    
        [DbFunction("The_State_Duma_Entities", "DistributionOfHelpersIncludeAges")]
        public virtual IQueryable<DistributionOfHelpersIncludeAges_Result> DistributionOfHelpersIncludeAges(Nullable<int> sozyv, Nullable<int> age_start, Nullable<int> age_end)
        {
            var sozyvParameter = sozyv.HasValue ?
                new ObjectParameter("Sozyv", sozyv) :
                new ObjectParameter("Sozyv", typeof(int));
    
            var age_startParameter = age_start.HasValue ?
                new ObjectParameter("Age_start", age_start) :
                new ObjectParameter("Age_start", typeof(int));
    
            var age_endParameter = age_end.HasValue ?
                new ObjectParameter("Age_end", age_end) :
                new ObjectParameter("Age_end", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DistributionOfHelpersIncludeAges_Result>("[The_State_Duma_Entities].[DistributionOfHelpersIncludeAges](@Sozyv, @Age_start, @Age_end)", sozyvParameter, age_startParameter, age_endParameter);
        }
    
        public virtual ObjectResult<FactionsPercentage_Result> FactionsPercentage(Nullable<int> sozyv)
        {
            var sozyvParameter = sozyv.HasValue ?
                new ObjectParameter("Sozyv", sozyv) :
                new ObjectParameter("Sozyv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FactionsPercentage_Result>("FactionsPercentage", sozyvParameter);
        }
    
        public virtual ObjectResult<GetSozyvyStatus_Result> GetSozyvyStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSozyvyStatus_Result>("GetSozyvyStatus");
        }
    
        public virtual ObjectResult<SozyvyPercentage_Result> SozyvyPercentage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SozyvyPercentage_Result>("SozyvyPercentage");
        }
    
        public virtual ObjectResult<SozyvyStats_Result> SozyvyStats()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SozyvyStats_Result>("SozyvyStats");
        }
    
        public virtual int SozyvyVozrastnoi_sostav()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SozyvyVozrastnoi_sostav");
        }
    
        public virtual ObjectResult<SozyvyVozrastnoi_sostav_new_Result> SozyvyVozrastnoi_sostav_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SozyvyVozrastnoi_sostav_new_Result>("SozyvyVozrastnoi_sostav_new");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int UpdateSessionStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateSessionStatus");
        }
    
        public virtual int Vozrastnoi_sostav(Nullable<int> sozyv)
        {
            var sozyvParameter = sozyv.HasValue ?
                new ObjectParameter("Sozyv", sozyv) :
                new ObjectParameter("Sozyv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Vozrastnoi_sostav", sozyvParameter);
        }
    
        public virtual ObjectResult<Vozrastnoi_sostav_new_Result> Vozrastnoi_sostav_new(Nullable<int> sozyv)
        {
            var sozyvParameter = sozyv.HasValue ?
                new ObjectParameter("Sozyv", sozyv) :
                new ObjectParameter("Sozyv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Vozrastnoi_sostav_new_Result>("Vozrastnoi_sostav_new", sozyvParameter);
        }
    }
}
