//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Versiya_ZP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Versiya_ZP()
        {
            this.Gruppovaya_rabota = new HashSet<Gruppovaya_rabota>();
            this.Gruppovaya_rabota1 = new HashSet<Gruppovaya_rabota>();
            this.Otvetstvennie_za_versiyu = new HashSet<Otvetstvennie_za_versiyu>();
        }
    
        public int ID { get; set; }
        public int Nomer { get; set; }
        public int Zakonoproekt { get; set; }
        public Nullable<System.DateTime> Data_razravotki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gruppovaya_rabota> Gruppovaya_rabota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gruppovaya_rabota> Gruppovaya_rabota1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otvetstvennie_za_versiyu> Otvetstvennie_za_versiyu { get; set; }
        public virtual Zakonoproekt Zakonoproekt1 { get; set; }
    }
}
