//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Versiya_feature
    {
        public int ID { get; set; }
        public int Otvetstvennost { get; set; }
        public int Deputat { get; set; }
        public string Opisanie { get; set; }
    
        public virtual Deputaty Deputaty { get; set; }
        public virtual Otvetstvennie_za_versiyu Otvetstvennie_za_versiyu { get; set; }
    }
}
