//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zasedanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zasedanie()
        {
            this.Gruppovaya_rabota = new HashSet<Gruppovaya_rabota>();
            this.Rassmotrenie_ZP = new HashSet<Rassmotrenie_ZP>();
        }
    
        public int Nomer { get; set; }
        public string Naimenovanie { get; set; }
        public string Tip { get; set; }
        public System.DateTime Data_provedeniya { get; set; }
        public System.TimeSpan Vremya_nachala { get; set; }
        public System.TimeSpan Vremya_konca { get; set; }
        public string Status_zasedaniya { get; set; }
        public int Mesto_provedeniya { get; set; }
        public int Nomer_sozyva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gruppovaya_rabota> Gruppovaya_rabota { get; set; }
        public virtual Mesto_provedeniya Mesto_provedeniya1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rassmotrenie_ZP> Rassmotrenie_ZP { get; set; }
        public virtual Sozyvy Sozyvy { get; set; }
    }
}
